In [21]:
import numpy as np
array1 = np.array([1,2,3])
print(type(array1))
print(array1.shape)


print('array1 : {0}차원'.format(array1.ndim))

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.ones((3,2), dtype='int32')
print(zero_array)

array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,1)
print(array2)

arr = np.array([3,1,9,5])
sort_indices = np.argsort(arr)
print(arr)
print(sort_indices)

<class 'numpy.ndarray'>
(3,)
array1 : 1차원
[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[[1 1]
 [1 1]
 [1 1]]
[0 1 2 3 4 5 6 7 8 9]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[3 1 9 5]
[1 0 3 2]
